In [78]:
import numpy as np
import pandas as pd
import seaborn as sns
from ucimlrepo import fetch_ucirepo 
from sklearn import metrics as skmetrics
from aif360 import metrics as fairmetrics
from aif360.datasets import BinaryLabelDataset
from sklearn.metrics import accuracy_score

In [80]:
#data_url = 'https://raw.githubusercontent.com/socialfoundations/folktables/refs/heads/main/adult_reconstruction.csv'
#data_df = pd.read_csv(data_url)

In [82]:
models_only_df =  pd.read_csv('https://raw.githubusercontent.com/rhodyprog4ds/portfolio-fall24-mayageva1/refs/heads/assignment6/adult_models_only.csv?token=GHSAT0AAAAAACX7NBFN2IELBP42ZPYBYQR4ZYX2Q7Q')

In [83]:
models_only_df.head(2)

,id,LR_income>=10k,LR_income>=20k,LR_income>=30k,LR_income>=40k,LR_income>=50k,LR_income>=60k,LR_income>=70k,LR_income>=80k,LR_income>=90k,...,GPR_income>=90k,RPR_income>=10k,RPR_income>=20k,RPR_income>=30k,RPR_income>=40k,RPR_income>=50k,RPR_income>=60k,RPR_income>=70k,RPR_income>=80k,RPR_income>=90k
0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [119]:
models_only_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9897 entries, 0 to 9896
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               9897 non-null   int64
 1   LR_income>=10k   9897 non-null   float64
 2   LR_income>=20k   9897 non-null   float64
 3   LR_income>=30k   9897 non-null   float64
 4   LR_income>=40k   9897 non-null   float64
 5   LR_income>=50k   9897 non-null   float64
 6   LR_income>=60k   9897 non-null   float64
 7   LR_income>=70k   9897 non-null   float64
 8   LR_income>=80k   9897 non-null   float64
 9   LR_income>=90k   9897 non-null   float64
 10  GPR_income>=10k  9897 non-null   float64
 11  GPR_income>=20k  9897 non-null   float64
 12  GPR_income>=30k  9897 non-null   float64
 13  GPR_income>=40k  9897 non-null   float64
 14  GPR_income>=50k  9897 non-null   float64
 15  GPR_income>=60k  9897 non-null   float64
 16  GPR_income>=70k  9897 non-null   float64
 17  GPR_income>=80k  9897 non-null   float64
 18  GPR_income>=90k  9897 non-null   float64
 19  RPR_income>=10k  9897 non-null   float64
 20  RPR_income>=20k  9897 non-null   float64
 21  RPR_income>=30k  9897 non-null   float64
 22  RPR_income>=40k  9897 non-null   float64
 23  RPR_income>=50k  9897 non-null   float64
 24  RPR_income>=60k  9897 non-null   float64
 25  RPR_income>=70k  9897 non-null   float64
 26  RPR_income>=80k  9897 non-null   float64
 27  RPR_income>=90k  9897 non-null   float64
dtypes: float64(27), int64(1)
memory usage: 2.1 MB

In [86]:
reconstruction_df = pd.read_csv('https://raw.githubusercontent.com/rhodyprog4ds/portfolio-fall24-mayageva1/refs/heads/assignment6/adult_reconstruction_bin.csv?token=GHSAT0AAAAAACX7NBFNY6IAPTRVD4F77QI6ZYX2S2Q')
reconstruction_df.head(2)

,Unnamed: 0,hours-per-week,age,capital-gain,capital-loss,workclass,education,education-num,marital-status,relationship,...,occupation,income>=10k,income>=20k,income>=30k,income>=40k,income>=50k,income>=60k,income>=70k,income>=80k,income>=90k
0,0,20,40,0,0,Private,Bachelors,13,Married-civ-spouse,Wife,...,Tech-support,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1,40,21,0,0,Private,Some-college,10,Divorced,Own-child,...,Craft-repair,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [121]:
reconstruction_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45849 entries, 0 to 49530
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      45849 non-null  int64
 1   hours-per-week  45849 non-null  int64
 2   age             45849 non-null  int64
 3   capital-gain    45849 non-null  int64
 4   capital-loss    45849 non-null  int64
 5   workclass       45849 non-null  object
 6   education       45849 non-null  object
 7   education-num   45849 non-null  int64
 8   marital-status  45849 non-null  object
 9   relationship    45849 non-null  object
 10  race            45849 non-null  object
 11  gender          45849 non-null  object
 12  native-country  45849 non-null  object
 13  occupation      45849 non-null  object
 14  income>=10k     45849 non-null  float64
 15  income>=20k     45849 non-null  float64
 16  income>=30k     45849 non-null  float64
 17  income>=40k     45849 non-null  float64
 18  income>=50k     45849 non-null  float64
 19  income>=60k     45849 non-null  float64
 20  income>=70k     45849 non-null  float64
 21  income>=80k     45849 non-null  float64
 22  income>=90k     45849 non-null  float64
dtypes: float64(9), int64(6), object(8)
memory usage: 8.4+ MB

In [88]:
# fetch dataset 
#predictions = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
#X = predictions.data.features 
#y = predictions.data.targets 
#predictions_df = pd.concat([X, y], axis=1)

In [50]:
#data_df.head()

In [54]:
#predictions_df.head()

In [56]:
#data_df['income'] = data_df['income'].apply(lambda x: '<=50K' if x <= 50000 else '>50K')
#models_df = pd.merge(data_df, predictions_df, on = 'income')
#models_df.head()

In [58]:
#predictions_df.info()

In [60]:
#predictions_df['income'].value_counts()

In [62]:
#predictions_df['income'] = predictions_df['income'].replace('<=50K.','<=50K')
#predictions_df['income'] = predictions_df['income'].replace('>50K.','>50K')
#predictions_df['income'].value_counts()

In your audit, use at least three different performance metrics. Compare and contrast performance in those metrics across racial or gender groups. Include easy to read tables with your performance metrics and interpretations of the model’s overall performance and any disparities that could be understood by a general audience.

In [92]:
my_num = 17# pick a number
np.random.seed(my_num)
models_to_audit = np.random.choice(models_only_df.columns,2)
models_to_audit

array(['GPR_income>=60k', 'GPR_income>=80k'], dtype=object)

In [102]:
gender_num_map = {r:i for i,r, in enumerate(reconstruction_df['gender'].value_counts().index)}
reconstruction_df['gender'].replace(gender_num_map)
reconstruction_df['gender'].value_counts()

/var/folders/x1/y6r3qzx55_xbw53ywjfty_y80000gn/T/ipykernel_18088/3459858099.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  reconstruction_df['gender'].replace(gender_num_map)

gender
Male      33174
Female    16357
Name: count, dtype: int64

In [7]:
# Perform an inner join on the unique identifier, keeping only rows present in both dataframes
#models_df = pd.merge(reconstruction_df, models_only_df, left_on='income>=60k', right_on='GPR_income>=60k', how='inner')
#models_df.head()
reconstruction_df = reconstruction_df.drop(df.tail(39633).index,
        inplace = True)

NameError: name 'reconstruction_df' is not defined

In [115]:
accuracy = skmetrics.accuracy_score(models_only_df['GPR_income>=60k'],
                         reconstruction_df['income>=60k'])
accuracy

ValueError: Found input variables with inconsistent numbers of samples: [9897, 45849]

Which of the two would you think is better to deploy?

##