In [2]:
import pandas as pd
from sklearn import metrics
import seaborn as sns

In [6]:
compas_clean_url = 'https://raw.githubusercontent.com/ml4sts/outreach-compas/main/data/compas_c.csv'
compas_df = pd.read_csv(compas_clean_url)
compas_df.head()

,id,age,c_charge_degree,race,age_cat,score_text,sex,priors_count,days_b_screening_arrest,decile_score,is_recid,two_year_recid,c_jail_in,c_jail_out,length_of_stay
0,3,34,F,African-American,25 - 45,Low,Male,0,-1.0,3,1,1,2013-01-26 03:45:27,2013-02-05 05:36:53,10
1,4,24,F,African-American,Less than 25,Low,Male,4,-1.0,4,1,1,2013-04-13 04:58:34,2013-04-14 07:02:04,1
2,8,41,F,Caucasian,25 - 45,Medium,Male,14,-1.0,6,1,1,2014-02-18 05:08:24,2014-02-24 12:18:30,6
3,10,39,M,Caucasian,25 - 45,Low,Female,0,-1.0,1,0,0,2014-03-15 05:35:34,2014-03-18 04:28:46,2
4,14,27,F,Caucasian,25 - 45,Low,Male,0,-1.0,4,0,0,2013-11-25 06:31:06,2013-11-26 08:26:57,1

In [8]:
pd.get_dummies(compas_df['score_text'])

       High    Low  Medium
0     False   True   False
1     False   True   False
2     False  False    True
3     False   True   False
4     False   True   False
...     ...    ...     ...
5273  False   True   False
5274   True  False   False
5275  False  False    True
5276  False   True   False
5277  False   True   False

[5278 rows x 3 columns]

In [10]:
compas_onehot = pd.concat([compas_df,pd.get_dummies(compas_df['score_text'])],axis=1)

In [12]:
compas_onehot.groupby('score_text')['decile_score'].agg(['min','max'])

            min  max
score_text
High          8   10
Low           1    4
Medium        5    7

In [14]:
compas_onehot['MedHigh'] = compas_onehot['High'] + compas_onehot['Medium']

In [16]:
metrics.accuracy_score(compas_onehot['two_year_recid'],compas_onehot['MedHigh'])

0.6582038651004168

In [18]:
metrics.confusion_matrix(compas_onehot['two_year_recid'],compas_onehot['MedHigh'])

array([[1872,  923],
       [ 881, 1602]])