# Exploratory Data Analysis

In [3]:
import pandas as pd

In [4]:
carbon_data_url = 'https://github.com/rfordatascience/tidytuesday/raw/master/data/2024/2024-05-21/emissions.csv'

In [5]:
carbon_df = pd.read_csv(carbon_data_url)

In [6]:
carbon_df.head()

,year,parent_entity,parent_type,commodity,production_value,production_unit,total_emissions_MtCO2e
0,1962,Abu Dhabi National Oil Company,State-owned Entity,Oil & NGL,0.91250,Million bbl/yr,0.363885
1,1962,Abu Dhabi National Oil Company,State-owned Entity,Natural Gas,1.84325,Bcf/yr,0.134355
2,1963,Abu Dhabi National Oil Company,State-owned Entity,Oil & NGL,1.82500,Million bbl/yr,0.727770
3,1963,Abu Dhabi National Oil Company,State-owned Entity,Natural Gas,4.42380,Bcf/yr,0.322453
4,1964,Abu Dhabi National Oil Company,State-owned Entity,Oil & NGL,7.30000,Million bbl/yr,2.911079

In [7]:
carbon_df.sample(5)

,year,parent_entity,parent_type,commodity,production_value,production_unit,total_emissions_MtCO2e
6338,2009,Naftogaz,State-owned Entity,Oil & NGL,25.874900,Million bbl/yr,10.318338
10533,2003,Singareni Collieries,State-owned Entity,Bituminous Coal,0.975096,Million tonnes/yr,2.646547
4327,1929,ExxonMobil,Investor-owned Company,Oil & NGL,111.093444,Million bbl/yr,44.301610
9720,1990,RWE,Investor-owned Company,Lignite Coal,103.000000,Million tonnes/yr,137.938642
11082,1996,Suncor Energy,Investor-owned Company,Natural Gas,342.400000,Bcf/yr,24.957670

In [8]:
carbon_df.describe()

               year  production_value  total_emissions_MtCO2e
count  12551.000000      12551.000000            12551.000000
mean    1987.148116        412.712258              113.219734
std       29.202455       1357.569683              329.812666
min     1854.000000          0.004398                0.000321
25%     1973.000000         10.601353                8.785294
50%     1994.000000         63.203536               33.058688
75%     2009.000000        320.664764              102.154596
max     2022.000000      27192.000000             8646.905949

In [9]:
#carbon_df.quantile() doesnt work

In [14]:
carbon_df['production_value'].quantile(.25)

10.6013534253315

In [16]:
carbon_df['total_emissions_MtCO2e'].mean()

113.21973391166483

In [18]:
carbon_df['parent_type'].value_counts()

parent_type
Investor-owned Company    6583
State-owned Entity        3914
Nation State              2054
Name: count, dtype: int64

In [20]:
carbon_df['parent_type'].mode()

0    Investor-owned Company
Name: parent_type, dtype: object

is it reasonable to compare and use all of the 'commodity' types in the data

In [22]:
carbon_df["commodity"].value_counts()

commodity
Oil & NGL              3733
Natural Gas            3452
Bituminous Coal        1370
Metallurgical Coal     1073
Lignite Coal           1008
Sub-Bituminous Coal     673
Thermal Coal            611
Anthracite Coal         368
Cement                  263
Name: count, dtype: int64

In [30]:
carbon_df["commodity_simple"] = carbon_df['commodity'].apply(lambda s: s if not("Coal" in s)

SyntaxError: incomplete input (2783279477.py, line 1)

In [32]:
coal_strip = lambda s: if not("Coal" in s)

SyntaxError: invalid syntax (4281770137.py, line 1)

In [28]:
coal_strip("Metallurgical Coal")

NameError: name 'coal_strip' is not defined

In [ ]:
i am getting TypeError: 'DataFrame' object is not callable