In [2]:
import pandas as pd
import numpy as np

exploring the pokemon data set. display first 4 rows and find a numpy array of only the numerical data

In [4]:
pokemon_data_url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/Pokemon.csv'

In [5]:
pokemon_df = pd.read_csv(pokemon_data_url,index_col=0)

In [6]:
pokemon_df.head(4)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [7]:
#I found the select_dtype function on the pandas database
numerical_df = pokemon_df.select_dtypes(include=[np.number])
numerical_array = numerical_df.to_numpy()

In [8]:
numerical_array

array([[318,  45,  49, ...,  65,  45,   1],
       [405,  60,  62, ...,  80,  60,   1],
       [525,  80,  82, ..., 100,  80,   1],
       ...,
       [600,  80, 110, ..., 130,  70,   6],
       [680,  80, 160, ..., 130,  80,   6],
       [600,  80, 110, ...,  90,  70,   6]])

was the format that the data was provided in a good format? why or why not?: As you can see the numerical data array prints does not have a header so all you see is numbers but you can really be sure what they mean. It also doesnt display all the data at once because the middle part is cut out and replaced with "..."

exploring the parks dataset. Display the heading with last 3 rows , display the pandas datatype for last 3 rows.

In [11]:
parks_data_url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/parks.csv'

In [12]:
parks_df = pd.read_csv(parks_data_url)

In [13]:
parks_df.tail(3)

,Park Code,Park Name,State,Acres,Latitude,Longitude
53,YELL,Yellowstone National Park,"WY, MT, ID",2219791,44.60,-110.50
54,YOSE,Yosemite National Park,CA,761266,37.83,-119.50
55,ZION,Zion National Park,UT,146598,37.30,-113.05

In [53]:
parks_df.dtypes

Park Code     object
Park Name     object
State         object
Acres          int64
Latitude     float64
Longitude    float64
dtype: object

Are there any variables where pandas may have read in the data as a datatype that’s not what you expect (eg a numerical column mistaken for strings)? If so, investigate and try to figure out why.: The park code is read as an object even though it should be an integer. The park name and state should be strings but they are also listed as an object.

exploring the github issues database. save every third row of two columns and save it into a new dataframe

In [17]:
issues_data_url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/Github_Stats/issues.csv'

In [18]:
issues_df = pd.read_csv(issues_data_url)

In [19]:
thirdrows = issues_df.iloc[3::3][['name', 'count']]

In [20]:
thirdrows

            name  count
3            PHP    560
6              C    163
9     JavaScript   4003
12           C++   1941
15            C#    729
...          ...    ...
3360       xBase    156
3363         QML    118
3366      Python    411
3369  JavaScript    220
3372  TypeScript    169

[1124 rows x 2 columns]

Exploring data files

In [22]:
german_data_url = 'https://raw.githubusercontent.com/rhodyprog4ds/portfolio-fall24-mayageva1/refs/heads/assignment2/data/german.data?token=GHSAT0AAAAAACXKG3MSZE7S2N6XG6QARJWMZXNZC5Q'

In [26]:
german_df = pd.read_csv(german_data_url, sep=' ')

I noticed that this dataset is seperate by spaces instead of commas, and I couldnt change the data file to be an actual csv.
To fix this, I added "sep= ' '" as one of the parameters of read_csv. This parameter tells it so seperate each value by a space
rather than the default comma.
I learned how to do this in one of my previous csc classes.

In [30]:
communication_data_url = 'https://raw.githubusercontent.com/rhodyprog4ds/portfolio-fall24-mayageva1/refs/heads/assignment2/data/communication.csv?token=GHSAT0AAAAAACXKG3MS4EIZ67QN5XDZJQWMZXNYUAQ'

In [41]:
comm_df = pd.read_csv(communication_data_url, on_bad_lines = 'skip')

When reading through the error message I got when trying to read this csv file, I noticed that one of the lines had one more value than all of the other ones, which is what was causing the error. I looked through the pandas database for a fix for this, and i found the following line: "on_bad_lines='skip'". This is used as a parameter for the read_csv, and it fixed the error.